//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbOperations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeParserEntities : DbContext
    {
        public ResumeParserEntities()
            : base("name=ResumeParserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Keywords> Keywords { get; set; }
        public virtual DbSet<Resumes> Resumes { get; set; }
        public virtual DbSet<ResumeValues> ResumeValues { get; set; }
    }
}
