//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeValues
    {
        public System.Guid ResumeId { get; set; }
        public System.Guid KeywordId { get; set; }
        public string KeywordValue { get; set; }
    
        public virtual Keywords Keywords { get; set; }
        public virtual Resumes Resumes { get; set; }
    }
}
