//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resumes()
        {
            this.ResumeValues = new HashSet<ResumeValues>();
        }
    
        public System.Guid ResumeId { get; set; }
        public string ResumeContents { get; set; }
        public string FilePath { get; set; }
        public string ResumeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResumeValues> ResumeValues { get; set; }
    }
}
